name: Master

on:
  push:
    branches:
      - 'master'
      - 'rc/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - name: Init NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - name: Install Packages
        run: npm ci
        shell: bash
      - name: Test
        run: npm test
        shell: bash
      - name: Build
        run: npm run build:docs
      - name: Check generated site integrity
        run: npm run check:site
      - name: Deploy image
        uses: valitydev/action-deploy-docker@v1.0.16
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile-path: .
